Checkpoint 1
SemyonPanenko/HyperBook pull request #2
Opened 2022-03-20 03:51 UTC by SemyonPanenko

2022-03-28 13:30 UTC, linlit commented
0) можно диаграмму картинкой или пдфкой хотя бы?
пока все, что могу сказать без диаграммы:
1) касты в проектах по ООП указывают почти наверное на плохую архитектуру
2) все строки-константы с сообщениями и тд лучше вынести в файл/енам/etc, чтобы не было магических строк-констант, при желании отредачить не надо было искать непонятно где нужную строку, и была понятна природа строк (например, если бы эта строка создавалась не на клиенте, а лежала в файле SignUpMessagesEnum - было бы понятно, что за строка и зачем она существует)

2022-03-31 17:43 UTC, akhtyamovpavel requested changes
Добрый день!

Посмотрел проект - для первой версии очень даже хорошо! Оставил некоторые комментарии по коду - если что, можно обращаться в ЛС!

За текущую версию могу поставить 8.

Если есть желание добить текущую итерацию - welcome! Буду ждать обновленную версию ко второй части задания!

P.S. Хотелось ввести команду, но не получилось

2022-03-31 17:43 UTC, akhtyamovpavel commented on sources/ConsoleInterface.cpp
> +    std::cout << "All the preparations were completed and I am ready to listen to your commands\n";
Сколько времени необходимо для того, чтобы увидеть команду? Я не дождался

2022-04-01 08:13 UTC, SemyonPanenko commented
>     1. касты в проектах по ООП указывают почти наверное на плохую архитектуру

А как иначе? Мы хотим визуализировать все виды контента одной функцией. Для этого она должна принимать ссылку на контент (или указатель). Но разные виды контента визуализируются по разному, поэтому нам нужно как-то понять, какой именно контент нам подсунули, и умеем ли мы его обрабатывать. Если это прям анти-паттерн, я попробую переделать, но когда мы писали фигуры с Мещериным, он вроде не ругался на динамик каст.

2022-04-01 08:14 UTC, SemyonPanenko commented
> 0. можно диаграмму картинкой или пдфкой хотя бы?
>        пока все, что могу сказать без диаграммы:

>     2. все строки-константы с сообщениями и тд лучше вынести в файл/енам/etc, чтобы не было магических строк-констант, при желании отредачить не надо было искать непонятно где нужную строку, и была понятна природа строк (например, если бы эта строка создавалась не на клиенте, а лежала в файле SignUpMessagesEnum - было бы понятно, что за строка и зачем она существует)

Сделано

2022-04-02 09:11 UTC, linlit commented on sources/ConsoleVisualizer.cpp
> +    auto to_text_ptr = dynamic_cast<TextContent *const>(text_content);
почему? зачем?

2022-04-02 09:12 UTC, linlit commented on sources/main.cpp
> +    delete ci;
зачем напрямую вызывать dalete?

2022-04-02 09:16 UTC, linlit commented
> 

Мещерин должен был вас научить кастам, да, это в его программе :)
а у нас другая парадигма: мы строим архитектуру так, чтобы к кастам не надо было прибегать, например наследованием.

2022-04-02 09:16 UTC, linlit commented
в остальном для первого этапа мне все нравится, ставлю 9

2022-04-02 09:17 UTC, merged